# 22/1/16 (월요일)

## class

In [1]:
#class
#사용자 정의 객체를 만들기 위한 주형
#정의는 보통 클래스 인스턴스를 대상으로 연산하는 메서드 정의 포함

class Class_Name:
    def method_name(self):
        method_body
    
    class_body
    ...

NameError: name 'class_body' is not defined

In [2]:
number = int(10)
print(type(number))

~~~



<class 'int'>


In [3]:
#클래스 속성
__init__메서드는 인스턴스를 만들 때 호출되는 특별한 메서드
__init__은 initalize의 줄임말로 인스턴스(객체)를 초기화(메모리에 공간을 할당하고 값을 부여함)

class Persson:
    def __init__(self):
        ~~~~~~~~

SyntaxError: invalid syntax (3436596626.py, line 2)

In [9]:
#속성을 접근할 때 self.
#지금은 class에 형태가 없다고 생각하기
class Student:
    pass

#stu_a와 b는 독립적으로 존재함
stu_a = Student() #class로 부터 인스턴스 초기화
stu_b = Student() #class로 부터 인스턴스 초기화

stu_a.hello = "안녕" #.hello는 속성을 추가해준거임
print(stu_a.hello)

print(stu_b.hello) #아무것도 할당되지 않아 오류날거임


안녕


AttributeError: 'Student' object has no attribute 'hello'

In [10]:
#예제

class Student:
    def __init__(self):
        self.hello = "안녕하세요"


In [13]:

class Student:
    def __init__(self):
        self.hello = "안녕하세요"
    
    def greeclting(self):
        print(self.hello)

stu_a.greeting()
stu_b.greeting()

AttributeError: 'Student' object has no attribute 'greeting'

In [15]:
class Person:
    def __init__(self, param, param2):
        self.hello = "안녕하세요"

        
        
class Person:
    def __init__(self, name, age):
        #self.hello = "안녕하세요"
        self.name(40)
        self.age = age
        
p1 = Person("name1", 40)
p2 = Person("name2", 32)

AttributeError: 'Person' object has no attribute 'name'

In [ ]:
p1 = Person = "name1"
p1.age = 40

p2 = Person = "name2"
p2.age = 32

In [20]:
class Person:
    def __init__(self, name, age, address):
        self.hello = "안녕"
        self.name = name
        self.age = age
        self.adress = address
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
maria = Person("마리아", 20, "서울시 서초구 반포동")
maria.greeting()

print("이름 : ", maria.name)
print("나이 : ", maria.age)
print("주소 : ", maria.adress)
print(maria.__dict__)

안녕 제 이름은 마리아입니다.
이름 :  마리아
나이 :  20
주소 :  서울시 서초구 반포동
{'hello': '안녕', 'name': '마리아', 'age': 20, 'adress': '서울시 서초구 반포동'}


In [28]:
#연습
#내가한거 1)
class Person:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address
        
    # def greeting(self):
    #     print(f"{self.hello} 제 이름은 {self.name}입니다.")
    
maria = Person("마리아", 20, "서울시 강남구")
james = Person("제임스", 21, "서울시 구로구")

print("이름 : ", maria.name)
print("나이 : ", maria.age)
print("주소 : ", maria.address)
print("이름 : ", james.name)
print("나이 : ", james.age)
print("주소 : ", james.address)
# print(maria.__dict__)
print("첫번째 이름 : ", maria.name)
print("첫번째 나이 : ", maria.age)
print("첫번째 주소 : ", maria.address)
print("두번째 이름 : ", james.name)
print("두번째 나이 : ", james.age)
print("두번째주소 : ", james.address)



#내가한거 2)
class Person:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address
        
    def greeting(self):
        print(f"이름은 무엇인가요? : {self.name}")
        print(f"나이는 무엇인가요? : {self.age}")
        print(f"주소는 무엇인가요? : {self.address}")
        

maria = Person("마리아", 20, "서울시 강남구")
james = Person("제임스", 21, "서울시 구로구")

maria.greeting()
james.greeting()

print("첫번째 이름 : ", maria.name)
print("첫번째 나이 : ", maria.age)
print("첫번째 주소 : ", maria.address)
print("두번째 이름 : ", james.name)
print("두번째 나이 : ", james.age)
print("두번째주소 : ", james.address)







#선생님코드
class Person():
    abc = "abc"
    def __init__(self, name, age, address): #생성자
        self.hello = "안녕하세요. 저는 사람입니다"
        self.name = name
        self.age = age
        self.address = address
    
    def greeting(self):
        print("{0} 저는 {1}입니다.".format(self.hello, self.name))
        
name = input("이름은 무엇인가요?")
age = input("나이는 무엇인가요?")
address = input("주소는 무엇인가요?")
maria = Person(name, age, address)

name = input("이름은 무엇인가요?")
age = input("나이는 무엇인가요?")
address = input("주소는 무엇인가요?")
james = Person(name, age, address)


print(f"첫번째 이름: {maria.name}")
print(f"첫번째 나이: {maria.age}")
print(f"첫번째 주소: {maria.address}")

print(f"두번째 이름: {james.name}")
print(f"두번째 나이: {james.age}")
print(f"두번째 주소: {james.address}")

이름 :  마리아
나이 :  20
주소 :  서울시 강남구
이름 :  제임스
나이 :  21
주소 :  서울시 구로구
첫번째 이름 :  마리아
첫번째 나이 :  20
첫번째 주소 :  서울시 강남구
두번째 이름 :  제임스
두번째 나이 :  21
두번째주소 :  서울시 구로구
이름은 무엇인가요? : 마리아
나이는 무엇인가요? : 20
주소는 무엇인가요? : 서울시 강남구
이름은 무엇인가요? : 제임스
나이는 무엇인가요? : 21
주소는 무엇인가요? : 서울시 구로구
첫번째 이름 :  마리아
첫번째 나이 :  20
첫번째 주소 :  서울시 강남구
두번째 이름 :  제임스
두번째 나이 :  21
두번째주소 :  서울시 구로구


In [34]:
#비공개 속성 사용하기
#인스턴스.속성 = 값 
#속성앞에 던더 붙이면 비공개 속성이 됨

#예제
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet #던더 여기에 쓰임, 얘는 class안에서만 사용할 수 있게 함
        
    def greeting(self): # __GREETING으로 해도 밖에서 못쓰게 만들어버림(비공개로 만들어버림), 메소드에도 적용 가능 
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
    def amount(self):
        print(self.__wallet)#비공개 속성은 클래스 안의 매서드에서만 접근 가능
        
        
a = Person3("엘", 1, "서울", 0)
print(a.name)
print(a.age)
print(a.address)
print()
# print(a.wallet) #월렛은 안나옴(던더 써서 비공개로 만들어서 없다고 나옴)

엘
1
서울


In [40]:
#예제
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet 
        
    def greeting(self): 
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
    def amount(self):
        print(self.__wallet)
        
    def pay(self, amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다")
            return
        self.__wallet -= amount
        
        
a = Person3("엘", 1, "서울", 0)


0
None
돈이 모자랍니다
None


In [49]:
#연습
#도움받은거

class Annie:
    def __init__(self, ch, ma, ap): #생성자
        self.ch = ch
        self.ma = ma
        self.ap = ap
    
    def tibbers(self):
        return ap * 0.65 + 400
        
ch, ma, ap = map(float, input("체력, 마나, AP를 입력하세요:").split()) #난 int로 잘못해줬었음, 꼭 맵으로 해줘야함 바로 list로 하니까 오류남
# list(int(input("체력, 마나, AP를 입력하세요")).split())   
annie = Annie(ch, ma, ap)

print(f"티버 : 피해량 {annie.tibbers()}")  # james.greeting() 메소드로 불러올떄는 소괄호 꼭 만들어 줘야함


체력, 마나, AP를 입력하세요: 511.68 334.0 298


티버 : 피해량 593.7


# numpy

In [ ]:
#숫자 데이터를 효과적으로 다룰 수 ㅇ
#데이터과학, 데이터분석에 많이 사용
#다차원 배열 자료구조 클래스인 ndarray클래스를 지원
#헹렬과 벡터

In [ ]:
#넘파이 배열

#배열 : 순서가 있는 같은 종류(타입)의 데이터가 저장되는 자료형
#리스트에 비해 적은 메모리로 많은 데이터를 빠르게 처리 가능

#리스트와 차이점 
##모든 요소(아이템)가 "자료형"이여야함(리스트는 다양한 자료형 섞어도 됨)
##요소의 개수를 바꿀 수 없음(리스트는 바꿀 수정, 삭제 가능)

#c로 구현된 내부 반복문 사용 
#벡터화 연산을 통해 복잡한 연산 수행 가능
#배열 인덱싱을 사용한 질의 기능 이용 -> 복잡한 수식 계산 가능

In [50]:
import numpy as np

In [61]:
#1차원 배열 만들기
## ndarry는 N-dimensional Array의 약자
## 다차원 배열 구조 지원

#넘파이 array메서드 인수로 시퀀스 자료형을 넣으면 ndarray클랙스 객체 즉, 넘파이 배열로 변환
#시퀀스자료형은 튜플보단 주로 리스트를 많이 활용
#밑 식은 리스트와 동일한 구조처럼 보임
#shape을 사용하면 넘파이 배열 모양 확인 가능
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
ar = np.array([i for i in range(10)])
print(ar)
print(ar.shape)
ar
type(ar)





[0 1 2 3 4 5 6 7 8 9]
(10,)
[ 0.1  5.   4.  12.   0.5]
int32


In [57]:
# !conda list 
#라이브러리 목록 확인하는 코드

In [64]:
#예제2
#정수와 실수가 혼합된리스트
#표현범위가 더 큰 자료형으로 변환
ar2 = np.array([0.1, 5, 12, 0.5])
print(ar2)


x = np.array([1, 2, 3])
y = np.array([1, 2, 3.0])
print(x.dtype)
print(y.dtype)

[ 0.1  5.  12.   0.5]
int32
float64


In [ ]:
#책 p122의 boolean타입이 틀림 -> "?"이거임, 교안에 있는게 맞는거

In [71]:
ar3 = np.array([i for i in range(3, 10, 3)], 'i8') # int8 byte * 8bit
print(ar3)
print(ar3.dtype)


ar4 = np.array([i for i in range(2, 10 ,2)], 'f8')
print(ar4)
print(ar4.dtype)


#'U8' 유니코드 8글자 자료형을 명시적으로 선언
#그래서 U5 U8
ar5 = np.array(["가나다라마" for i in range(5)], 'U5')
print(ar5)
print(ar5.dtype) #< U 5는 최대 5글자다라는걸 나타내주는애 , 숫자는 더 크게도 작게도 됨

[3 6 9]
int64
[2. 4. 6. 8.]
float64
['가나다라마' '가나다라마' '가나다라마' '가나다라마' '가나다라마']
<U5


In [66]:
ar4 = np.array([i for i in range(2, 10 ,2)], 'f8')
ar4

array([2., 4., 6., 8.])

In [72]:
#무한대 표현 -> np.inf  : 1을 0으로 나누려 할 때
#정의할 수 없는 숫자 -> np.nan : 0을 0으로 나누려할 떄

In [74]:
#벡터화 연산
#넘파이 배열 객체는-> 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산 지원
#벡터화 연산 사용 시 -> for반복문 없이 단 한번의 연산식으로 표현 가능
#예시
data = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x = np.array(data)
print(x)
print(2 * x)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [76]:
#list와 비교
#list
list_a = [i for i in range(3)]
print(list_a * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [81]:
#논리/비교연산자도 가능
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10)) #& = and

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [86]:
#2차원 배열 만들기
#행 먼저 보고 열 -> shape2,3 이면 2행 3열이라는 뜻
c = np.array([[0,1,2], [3,4,5]]) #2 * 3 array
print(c)
print(c.shape)
print(len(c)) #행
print(len(c[0])) #열

[[0 1 2]
 [3 4 5]]
(2, 3)
2
3


In [88]:
#연습
d = np.array([[10,20,30,40], [50, 60, 70, 80]]) #2 * 4 array
print(d)
print(d.shape)
print(len(d)) #행
print(len(d[0])) #열

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
2
4


In [97]:
#3차원배열
#깊이 * 행 * 열
#shape  4 , 3, 2면 깊이>행>열 순서 

#예제
#2 X 3 X 4
e = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
print(e)
print(e.shape)
print(len(e))
print(len(e[0]))
print(len(e[0][0]))


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
(2, 3, 4)
2
3
4


In [119]:
#배열의 인덱싱

#1)1차원
a = np.array([0, 1, 2, 3, 4, 5])
#a = np.array([i for i in range(5)])로 해도 됨
print(a[-1])



#2차원
b = ([[0, 1, 2], [3, 4, 5]])

print(b)

print(b[0][0])
print(b[0][1])
print(b[-1][-1])



#2차원, 슬라이싱과 콤마를 같이 사용하면 됨
b = np.array([[0, 1, 2, 3], [4, 5, 6, 7]]) 
#다른방법 -> np.array([i for i in range(8)]).reshape(2, 4)

print(b[0, :])
print(b[:, 1]) 
print(b[1, 1:])
print(b[:2, :2])




5
[[0, 1, 2], [3, 4, 5]]
0
1
5
[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [162]:
#연습
c = np.array([i for i in range(15)]).reshape(3, 5)

print(c[1, 2]) #7

print(c[-1, -1]) #14 

print(c[1, 1:3]) # [6 7]

print(c[1:3, 2]) #[7 12] -> 작은 리스트들도 단위로 슬라이싱 가능함. 그 안에 요소만 가능한게 아님

print(c[:2, -2:]) # [3 4] [8 9] ->시작:끝+1해야 내가 원하는 리스트까지 볼 수 있음

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [175]:
#배열생성
#넘파이는 몇가지 단순한 배열을 생성하는 메서드를 제공

#zeros, ones
#zeros_likem ones_like
#empty
#arange
#....
a = np.zeros(5)
print(a)

b = np.zeros((5, 2), dtype='i')
print(c)


# #문자열 배열도 가능하지만 모든 원소의 문자열 크기가 같아야함
# c = np.zeros(5), dtype = "U4".....다시


d = np.ones((2,3,4), dtype = "i8") #깊이 행 열 순서
d

e = np.ones_like(b, dtype = "f")
e

f = np.empty((4, 3))
f

[0. 0. 0. 0. 0.]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [180]:
#arange
np.arange(10)# 0...n-1

np.arange(3, 21, 2) #시작, 끝(포함안함), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [181]:
#전치연산
#2차원 배열의 전치 연산은 행과 열을 바꾸는 작업입니다. 이는 배열의 T속성으로 구할 수 있음, 메서드X
a = np.array([[1,2,3], [4,5,6]])
a....다시


array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
#배열의 크기 변형 -> reshape()
ex = np.arange(12)
ex.reshape(3,4) #(2,2,-1)도 됨

#다차원의 배열을 1차원으로 -> .flatten(), .ravel()
ex.flatten()
ex.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [197]:
#배열연결
#행의 수나 열의 수가 같은 두 개 이상의 배열을 연결해 더 큰 배열을 만들 때

#hstack, vstack, dstack, r_, c_, tile, hstack
#hstack은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결, 연결할 배열은 하나의 리스트에 담아야 함.



#vstack(열)합치기 : 
b1 = np.ones((2,3))
b2 = np.zeros((3,3))

print(b1)
print(b2)

np.vstack([b1, b2])



#dstack(깊이)합치기:
c1 = np.ones((3,4))
c2 = np.zeros((3, 4,))

print(c1)
print(c2)

np.dstack([c1,c2]) # 3 X 4 X 2배열



#배열연결 다시 정리해야함



# r_메서드
#hstack과 비슷하게 배열을 좌우로 연결
#인덱서라고도 부름(특수메서드)




#c_메서드
#배열ㅇ의 차원을 증가시킨 후 좌우로 연결
#1차원 배열을 연결하면 2차원 배열이 됨
np.c_[np.array([1,2,3]),np.array([4,5,6])]




#tile명령
#동일한 배열을 반복해 연결
a = np.array([[0,1,2], [3,4,5]])
np.tile(a,2)

np.tile(a, (3,2))



#

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [220]:
#연습
#내가한거
b1 = np.zeros((3,3)) #b1+b2
b2 = np.ones((3,2))
c = np.arange(10, 151, 10) #5개씩 자르기
print(b1)
print(b2)
print(c)

# np.vstack([b1, b2])



#선생님코드
zeros = np.zeros([3, 3])
ones = np.ones([3,2] )
numbers = np.reshape(np.arange(10 ,160, 10), (-3, -1))
res = np.tile(np.vstack([np.hstack~~~~]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150]


In [213]:
ex = np.arange(10, 151, 10)
ex

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [ ]:
#정답
a1 = np.zeros((3, 3))
a2 = np.ones((3, 2))
a3 = np.hstack([a1, a2])
a4 = np.arange(10, 160, 10)
a5 = a4.reshape(3, 5)
a6 = np.vstack([a3, a5])
a7 = np.vstack([a6, a6])
a7