# 22/1/17(화요일)

## class

In [2]:
import numpy as np

In [29]:
#연습
#도움받음

class Calculator: #인스턴스초기화, 여기서 괄화를 쓰게 되면 
    def __init__(self): #__init__초기화 할때 실행
        self.value = 0 #value는 속성
        
      
        
        
    def add(self, *args): #*args는 튜플형식 -> *args를 받아와야하는데 루프를 돌리거나 sum험수 쓰거나(np.sum()쓰는게 더 쉽고 빠름) 
        #왜 *args가 들어가야하는지 모르겠음
        a_sum = np.array(args) #왜 array하는지, args가 들어가는지 모르겠음
        self.value += np.sum(a_sum) #self.value가 왜 들어가야하는지 모르겠음
    

    def minus(self, *args):
        a_minus = np.array(args)
        self.value -= np.sum(a_minus)
        

    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")
        
    
        
c = Calculator() #class로부터 인스턴스를 초기화한다
c.add(100)
c.minus(10)
c.add([10, 20])
c.add(range(1, 6))
c.show_value()    

        
        
        
# Calculator.minus(20)

# c.show_value() #"현재 값은 80입니다."

# c.add()  #숫자를 입력해줒세요

# c.minus([10, 20])

# c.show_value()#"현재 값은 50입니다"

# c.add(range(1, 6))

# c.show_value()# "현재 값은 65입니다"






#선생님 코드
class Calculator:
    def __init__(self):
        self.value = 0 #밖에 vlaue = 0으로 두고 self만 써도 됨
    
    def add(self, *args):
        if len(args) > 0:
            num = np.array(args)
            self.value += np.sum(num)
        else:
            print("숫자를 입력해주세요")
    
    def minus(self, *args):
        if len(args) > 0:
            num = np.array(args)
            self.value -= np.sum(num)
        else:
            print("숫자를 입력해주세요")
            
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")
        
        
c = Calculator() #class로부터 인스턴스를 초기화한다
c.add(100)
c.minus(10)
# c.add([10, 20])
# c.add(range(1, 6))
c.show_value()    
    

현재 값은 135입니다.


In [32]:
class Calculator:
    def __init__(self):
        self.value = 0 #밖에 vlaue = 0으로 두고 self만 써도 됨
    
    def add(self, *args):
        if len(args) > 0:
            num = np.array(args)
            self.value += np.sum(num)
        else:
            print("숫자를 입력해주세요")
    
    def minus(self, *args):
        if len(args) > 0:
            num = np.array(args)
            self.value -= np.sum(num)
        else:
            print("숫자를 입력해주세요")
            
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")
        
        
c = Calculator() #class로부터 인스턴스를 초기화한다
c.add(100)
c.minus(10)
# c.add([10, 20])
# c.add(range(1, 6))
c.show_value()    


현재 값은 90입니다.


## numpy

In [38]:
#벡터화 연산

%%time #걸리는 시간 알려줌, 코드가 돌아가는데 걸린 시간을 알려줌


#사칙연산 뿐만 아니라 비교연산같은 논리연산도 벡터화 연산 가능

#all명령 : 일일히 비교 하는 것이 아닌 배열의 모든 원소가 다 같은지 알고 싶을 때 사용(전부같아야 True)




UsageError: Line magic function `%%time` not found.


In [40]:
#스칼라와 벡터/행렬의 곱셈

#배열에서 스칼라와 벡터/행렬의 곱도 선형대수에서 사용하는 식과 같이 표현 가능
x = np.arange(10)

~


#
a = np.array([1.0 , 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])
a*b

array([ 4., 10., 18.])

In [ ]:
#브로드캐스팅

#모양이 다른 배열간의 연산이 가능해 지도록 배열 크기를 변환시켜줌
#작은 배열이 더 큰 배열에 호환되는 모양으로 확장장

#규칙 예시 : 배열과 스칼라 값이 연산에서 결합될때


#브로드캐스팅 불가능한 경우에서 4의 약수인 2가 있을 때는 왜 안되는지 궁금, 아까는 한가지만 충족 되면 된다했는데 예시에선 1이 있는데 왜 안되는거지?



#차원축소연산 -> 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나옴
            # -> 예시로 10 X 5크기의 2차원 배열에 대해 행-평균을 구하면 10개 숫자를 가진 1차원 벡터가 나오면 이것을 차원축소연산이라고함

In [6]:
#차원 축소 연산

## sum() : 해당 배열의 합산 결과를 반환, 2차원 이상일 때는 axis키워드 인수 사용가능

#1)
x = np.array([1,3,2])
np.sum(x)

#2)
x = np.arange(12).reshape(3, -1)
print(x.sum(axis = 0))#행 간의 연산 결과를 구함.
print(x.sum(axis = 1)) #열 간의 연산 결과를 구함

[12 15 18 21]
[ 6 22 38]


In [13]:
## min() : 배열의 제일 작은 값(최소값) 반환, 2차원 이상일 땐 axis키워드 인수 사용가능

x = np.arange(20).reshape(2, 5, -1)

print(x.min)

print(x.min(axis = 0))

print(np.min(x, axis = 1)) #얜 왜 np로 바로 묶었지? : np를 사용하며 구조상관없이 전부다 가져와서 더할 수 있음

print(x.min(axis = 2))


<built-in method min of numpy.ndarray object at 0x0000024F9724D690>
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1]
 [10 11]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [10]:
## argmin() : 해당 배열의 제일 작은 값의 인덱스 반환, axis사용 가능

x = np.arange(20).reshape(2, 5, -1)

print(x.argmin)
print(x.argmin(axis = 0))
print(x.argmin(axis = 1))
print(x.argmin(axis = 2))

<built-in method argmin of numpy.ndarray object at 0x0000024F9724DC30>
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
## max() : 제일 큰 값 반환(최댓값), axis사용 가능

x = np.arange(20).reshape(2, 5, -1)

print(x.max)

print(x.max(axis = 0))

print(np.max(x, axis = 1)) #얜 왜 np로 바로 묶었지? : np를 사용하며 구조상관없이 전부다 가져와서 더할 수 있음, 왜 axis가 1일때만 np를 사용하지??????????????????????

print(x.max(axis = 2))


<built-in method max of numpy.ndarray object at 0x0000024F9724D810>
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[ 8  9]
 [18 19]]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [16]:
## argmax() : 제일 큰 값의 인덱스 반환 ,axis사용가능

x = np.arange(20).reshape(2, 5, -1)

print(x.argmax)
print(np.argmax(x))
print(x.argmax(axis = 0))
print(x.argmax(axis = 1))
print(np.argmax(x, axis = 1))
print(x.argmax(axis = 2))

<built-in method argmax of numpy.ndarray object at 0x0000024F9724D8D0>
19
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[4 4]
 [4 4]]
[[4 4]
 [4 4]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
## mena() : 평균 

## median() : 중앙값

## np.all() : 모든 요소 True면 True, 하나라도 False면 False

## np.any() : 하나라도 True면 True, 전부 Fasle여야 False



In [31]:
#연습

p = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
              [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
              [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
              [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
              [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

print(p.max())
print(p.sum(axis = 0))
print(p.max(axis = 0))
print(p.max(axis = 1))
print(p.mean(axis = 1))
print(p.min(axis = 1))

9.0
[20.1 27.  23.6 26.  28.2 26.5]
[8.2 8.8 8.  9.  7.7 8.9]
[8.  9.  8.9 8.2 8.9]
[5.33333333 5.11666667 5.71666667 4.11666667 4.95      ]
[1.1 2.7 0.7 0.2 2.7]


In [ ]:
#정렬

## np.sort() : 크기에 따라 정렬해 새로운 배열을 만들 수 있음, axis 사용 가능(0이면 행따로따로, 1이면 열따로따로)
#메서드 형태는 자체변환 [3, 6, 1, 4]이면 -> [1, 3, 4, 6]그냥 이대로만 리스트가 여러개 있어도 섞이지 않고 얘네에서만 순서만 다시 정렬해줌
















In [ ]:
## np.argsort() : 정렬로 바꾸는게아니라 순서만 알고 싶을때, 값이 작은것 순서대로 인덱스 번호로 출력됨 







In [32]:
# 고급인덱싱

In [1]:
#연습

score = np.array([[1, 2, 3, 4],
                  [46, 99, 100, 71],
                  [81, 59, 90, 100]])


score2 = score.argsort()

score = score[score2]



# s = a.argsort()
# a = a[s]
# b = b[s]

NameError: name 'np' is not defined

In [3]:
#데이터의 개수
## len() 사용하기

#표본평균
## np.mean() #평균

#표본분산
## np.var() #분산

#표준편차
## np.std(x)

#최대최소
## np.max/min()

#중앙값
## np.median(x)

#사분위수 : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬했을 떄 1/4, 2/4. 3/4 위치에 있는 수
#예시 : 100개 이면 25번쨰순서 즉 하위 25%, 2사분위수는 중앙값
## np.percentile()
### 1사분위(변수, 25), 2사분위(변수, 50), 3사분위(변수, 75) 

In [6]:
#난수 발생과 카운팅
## random number -> 전에 배운 random하고 다름(이름만 같고 다른아이임)

#시드설정하기
## 특정한 시작 숫자(기준이 되는 시작 숫자)
## np.random.seed()사용
## 인수로는 0과 같거나 큰 정수 넣기

np.random.seed(0)

np.random.rand(5)

np.random.rand(10)

np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [7]:
#데이터의 순서 바꾸기

# np.random.shuffle() : 한 번 사용하면 변수의 값이 바뀜 -> 자체 변환(in-place)

In [8]:
#데이터 샘플링
#이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것(표본선택, 샘플링)

#np.random.choice(a size = None, replace = True, p = None)

## a : 배열이면 원래의 데이터, 정수이면 arange(a)명령으로 데이터 생성
## size : 정수. 샘플숫자
## replace : 불리언, True이면 한번 선택한 데이터를 다시 선택 가능
## p : 배열, 각 데이터가 선택될 수 있는 확률


### 첫 인수를 정수 5로 전달하여 np.arange(5)의 결과들

np.random.choice(5, 5, replace = False) #shuffle명령과 같음, 처음5-1까지, 다음5 5개
np.random.choice(5, 3, replace = False) #3개만 선택
np.random.choice(5, 10) #반복해서 10개 선택
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) #선택 확률을 다르게 해서 10개 선택

array([2, 3, 3, 3, 3, 0, 3, 3, 2, 2])

In [9]:
#난수 생성

#대표적인 3가지 

#rand : 0부터 1사이의 균일 분포, 균일한 확률 분포로 실수 난수 생성
##숫자인수는 생성할 난수의 크기, shape을 가진행렬 생성
np.random.rand(10)

#randn:표준정규분포 : 기댓값(mean)이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수 생성
##인수 사용법은 rand와 동일
np.random.randn(10)
np.random.randn(3, 5) # 5개씩 3줄

#randint:균일 분포의 정수 난수, 얜 마지막(몇~몇까지 숫자 지정했을때) 숫자 포함이 안됨, 전에 로또할 때 배운 randint때는 포함됨
## np.random.randint(low, high = None, size = None)
##만약 high를 입력하지 않으면 ~~~~~~~~~~~~~~~~~~~~
np.random.randint(10, size = 10)
np.random.randint(10 ,20 , size = 10)
np.random.randint(10, 20, size = (3, 5)

array([0.75068614, 0.60783067, 0.32504723, 0.03842543, 0.63427406,
       0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033])

In [18]:
#연습


np.random.seed(0)

a = np.random.randint(0, 2, 100) #최대숫자 미포함

count = 0
for i in range(100):#0~99를 하면 100개, 0부터 시작한 이유는 배열인덱스가 0부터 시작해서 그리고 위에 a변수 길이를 100로 해둬서 
                    #100자리에 len(a)로 쓰면 더 효율적임, rnage안에 0부터 시작하면 이 0은 생략가능(써도 상관은 없음)
    if a[i] == 1:
        count += 1 #count상자 만든 곳에 1이 나올 때마다 1더해주기
        
print(count/100) #100번 던진 확률을 구하는 거니까 100나눠주기
# 1개수 세기(강직님은 conut nonzero쓰심)

0.56


In [23]:
#연습
np.random.seed(0)

j = np.random.randint(1, 7, 100) #최대숫자 미포함, 100번 반복
6
np.mean(j) # = j.mean()

3.42

In [26]:
#정수 데이터 카운팅

## unique() : 
###데이터에서 중복된 값을 제거, 중복되지 않는 값의 리스트를 출력, 인수를 True로 설정하면 각 값의 데이터 개수도 출력
###데이터가 존재하는 값에 대해서만 개수를 셈 -> 주사위를 10번 던졌을 때 6이 한번도 나오지 않으면 이 값을 0으로 세주지 않음(이땐 bincount써주는게 좋음)



## bincount() : 
###주사위를 던졌을 때 나오는 수처럼 특정 범위의 수인 경우 bincount함수에 minlength인수를 설정해 쓰는 것이 좋음
###0부터 minlenth -1까지의 숫자에 대해 각각 카운트 함, 데이터가 없을 경우 카운트 값으 0이 됨
np.bincount([1, 1, 2, 2, 2, 3], minlength = 6)

array([0, 2, 3, 1, 0, 0], dtype=int64)